classes_dict = {
    'affirmation' : 1,
    'decline' : 2,
    'weather':101,
    'language_barrier':9,
    'transfer_request':102,
    'calling_about': 103,
    'answering_machine': 3,
    'DNC' : 5, #
    'say_again': 11,
    'can_you_email' : 105,
    'who_are_you' : 106,
    'already' : 107,
    'DNQ' : 108,
    'GreetBack' : 16,
    'sorry_greeting': 15,
    'BUSY': 4, #
    'Not_Interested': 8,
    'are_you_bot': 14,
    'where_are_you_calling_from': 7,
    'not_decision_maker': 109,
    'greetings': 6,
    'scam':5, #return DNC
    'abusive': 5, #return DNC,
    'Afford': 12,
    'Insurance': 14,
    'rebuttal': 100,
    'None': 10,
    'complain_calls':5, # return DNC; customer complaining about calls,
    'hold_a_sec':4, # like busy
    'interested':1,
    'other':10,
    'transfer_request': 111,
    'where_get_number':112,
}
